// Auto-generated by build/build-mcp-data.mjs — do not edit
export const demosData = [
  {
    "slug": "accordion",
    "name": "Accordion",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "action-sheet",
    "name": "Action Sheet",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "area-chart",
    "name": "Area Chart",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "autocomplete",
    "name": "Autocomplete",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "badge",
    "name": "Badge",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "breadcrumbs",
    "name": "Breadcrumbs",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "buttons",
    "name": "Buttons",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "calendar",
    "name": "Calendar",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "calendar-page",
    "name": "Calendar Page",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "cards",
    "name": "Cards",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "cards-expandable",
    "name": "Cards Expandable",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "checkbox",
    "name": "Checkbox",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "chips",
    "name": "Chips",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "color-picker",
    "name": "Color Picker",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "color-themes",
    "name": "Color Themes",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "color-themes-generate",
    "name": "Color Themes Generate",
    "frameworks": [
      "core"
    ]
  },
  {
    "slug": "contacts-list",
    "name": "Contacts List",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "content-block",
    "name": "Content Block",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "data-table",
    "name": "Data Table",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "data-table-collapsible",
    "name": "Data Table Collapsible",
    "frameworks": [
      "core"
    ]
  },
  {
    "slug": "data-table-head-inputs",
    "name": "Data Table Head Inputs",
    "frameworks": [
      "core"
    ]
  },
  {
    "slug": "data-table-pagination-footer",
    "name": "Data Table Pagination Footer",
    "frameworks": [
      "core"
    ]
  },
  {
    "slug": "data-table-selectable",
    "name": "Data Table Selectable",
    "frameworks": [
      "core"
    ]
  },
  {
    "slug": "data-table-sortable",
    "name": "Data Table Sortable",
    "frameworks": [
      "core"
    ]
  },
  {
    "slug": "data-table-title",
    "name": "Data Table Title",
    "frameworks": [
      "core"
    ]
  },
  {
    "slug": "dialog",
    "name": "Dialog",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "fab",
    "name": "Fab",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "fab-morph",
    "name": "Fab Morph",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "form-data",
    "name": "Form Data",
    "frameworks": [
      "core"
    ]
  },
  {
    "slug": "form-storage",
    "name": "Form Storage",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "gauge",
    "name": "Gauge",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "grid",
    "name": "Grid",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "icons",
    "name": "Icons",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "infinite-scroll",
    "name": "Infinite Scroll",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "inputs",
    "name": "Inputs",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "list",
    "name": "List",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "list-button",
    "name": "List Button",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "list-index",
    "name": "List Index",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "login-screen",
    "name": "Login Screen",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "login-screen-page",
    "name": "Login Screen Page",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "master-detail-detail",
    "name": "Master Detail Detail",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "master-detail-master",
    "name": "Master Detail Master",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "menu-list",
    "name": "Menu List",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "messages",
    "name": "Messages",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "navbar",
    "name": "Navbar",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "navbar-api",
    "name": "Navbar Api",
    "frameworks": [
      "core"
    ]
  },
  {
    "slug": "navbar-fixed",
    "name": "Navbar Fixed",
    "frameworks": [
      "core"
    ]
  },
  {
    "slug": "navbar-hide-on-scroll",
    "name": "Navbar Hide On Scroll",
    "frameworks": [
      "core"
    ]
  },
  {
    "slug": "navbar-hide-scroll",
    "name": "Navbar Hide Scroll",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "navbar-large",
    "name": "Navbar Large",
    "frameworks": [
      "core"
    ]
  },
  {
    "slug": "navbar-large-transparent",
    "name": "Navbar Large Transparent",
    "frameworks": [
      "core"
    ]
  },
  {
    "slug": "navbar-transparent",
    "name": "Navbar Transparent",
    "frameworks": [
      "core"
    ]
  },
  {
    "slug": "notifications",
    "name": "Notifications",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "page-loader-component",
    "name": "Page Loader Component",
    "frameworks": [
      "core"
    ]
  },
  {
    "slug": "page-transitions",
    "name": "Page Transitions",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "page-transitions-effect",
    "name": "Page Transitions Effect",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "panel",
    "name": "Panel",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "panel-left",
    "name": "Panel Left",
    "frameworks": [
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "panel-right",
    "name": "Panel Right",
    "frameworks": [
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "photo-browser",
    "name": "Photo Browser",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "picker",
    "name": "Picker",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "pie-chart",
    "name": "Pie Chart",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "popover",
    "name": "Popover",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "popup",
    "name": "Popup",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "preloader",
    "name": "Preloader",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "progressbar",
    "name": "Progressbar",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "pull-to-refresh",
    "name": "Pull To Refresh",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "pull-to-refresh-bottom",
    "name": "Pull To Refresh Bottom",
    "frameworks": [
      "core"
    ]
  },
  {
    "slug": "radio",
    "name": "Radio",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "range",
    "name": "Range",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "routable-actions",
    "name": "Routable Actions",
    "frameworks": [
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "routable-modals",
    "name": "Routable Modals",
    "frameworks": [
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "routable-popup",
    "name": "Routable Popup",
    "frameworks": [
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "searchbar",
    "name": "Searchbar",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "searchbar-expandable",
    "name": "Searchbar Expandable",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "segmented",
    "name": "Segmented",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "sheet-modal",
    "name": "Sheet Modal",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "skeleton",
    "name": "Skeleton",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "smart-select",
    "name": "Smart Select",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "sortable",
    "name": "Sortable",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "stepper",
    "name": "Stepper",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "store",
    "name": "Store",
    "frameworks": [
      "vue",
      "react",
      "svelte",
      "core"
    ]
  },
  {
    "slug": "store_page",
    "name": "Store Page",
    "frameworks": [
      "core"
    ]
  },
  {
    "slug": "subnavbar",
    "name": "Subnavbar",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "subnavbar-title",
    "name": "Subnavbar Title",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "swipeout",
    "name": "Swipeout",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "swiper",
    "name": "Swiper",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "swiper-3d-coverflow",
    "name": "Swiper 3d Coverflow",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "swiper-3d-cube",
    "name": "Swiper 3d Cube",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "swiper-3d-flip",
    "name": "Swiper 3d Flip",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "swiper-fade",
    "name": "Swiper Fade",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "swiper-gallery",
    "name": "Swiper Gallery",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "swiper-horizontal",
    "name": "Swiper Horizontal",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "swiper-lazy",
    "name": "Swiper Lazy",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "swiper-loop",
    "name": "Swiper Loop",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "swiper-multiple",
    "name": "Swiper Multiple",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "swiper-nested",
    "name": "Swiper Nested",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "swiper-pagination-fraction",
    "name": "Swiper Pagination Fraction",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "swiper-pagination-progress",
    "name": "Swiper Pagination Progress",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "swiper-parallax",
    "name": "Swiper Parallax",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "swiper-scrollbar",
    "name": "Swiper Scrollbar",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "swiper-space-between",
    "name": "Swiper Space Between",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "swiper-vertical",
    "name": "Swiper Vertical",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "swiper-zoom",
    "name": "Swiper Zoom",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "tabbar",
    "name": "Tabbar",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "tabbar-icons",
    "name": "Tabbar Icons",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "tabbar-scrollable",
    "name": "Tabbar Scrollable",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "tabs",
    "name": "Tabs",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "tabs-animated",
    "name": "Tabs Animated",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "tabs-routable",
    "name": "Tabs Routable",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "tabs-static",
    "name": "Tabs Static",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "tabs-swipeable",
    "name": "Tabs Swipeable",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "text-editor",
    "name": "Text Editor",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "timeline",
    "name": "Timeline",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "toast",
    "name": "Toast",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "toggle",
    "name": "Toggle",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "toolbar-hide-scroll",
    "name": "Toolbar Hide Scroll",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "toolbar-tabbar",
    "name": "Toolbar Tabbar",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "toolbar-tabbar-api",
    "name": "Toolbar Tabbar Api",
    "frameworks": [
      "core"
    ]
  },
  {
    "slug": "toolbar-tabbar-fixed",
    "name": "Toolbar Tabbar Fixed",
    "frameworks": [
      "core"
    ]
  },
  {
    "slug": "toolbar-tabbar-hide-on-scroll",
    "name": "Toolbar Tabbar Hide On Scroll",
    "frameworks": [
      "core"
    ]
  },
  {
    "slug": "toolbar-tabbar-static",
    "name": "Toolbar Tabbar Static",
    "frameworks": [
      "core"
    ]
  },
  {
    "slug": "toolbar-tabbar-tabbar",
    "name": "Toolbar Tabbar Tabbar",
    "frameworks": [
      "core"
    ]
  },
  {
    "slug": "toolbar-tabbar-tabbar-icons",
    "name": "Toolbar Tabbar Tabbar Icons",
    "frameworks": [
      "core"
    ]
  },
  {
    "slug": "toolbar-tabbar-tabbar-scrollable",
    "name": "Toolbar Tabbar Tabbar Scrollable",
    "frameworks": [
      "core"
    ]
  },
  {
    "slug": "tooltip",
    "name": "Tooltip",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "treeview",
    "name": "Treeview",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "view-page-transitions",
    "name": "View Page Transitions",
    "frameworks": [
      "core"
    ]
  },
  {
    "slug": "virtual-list",
    "name": "Virtual List",
    "frameworks": [
      "core",
      "vue",
      "react",
      "svelte"
    ]
  },
  {
    "slug": "virtual-list-vdom",
    "name": "Virtual List Vdom",
    "frameworks": [
      "core"
    ]
  }
] as const;
